(() => {
    const Admin = window.GMCAdmin = window.GMCAdmin || {};
    const $ = (selector, root = document) => root.querySelector(selector);
    const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
    const state = { tab: 'stats', orders: [], orderMeta: {}, orderPage: 1, orderStatus: '', menu: [], menuCategory: 'all', pendingReviews: [], approvedReviews: [], restaurant: null, confirmResolver: null };
    const statuses = ['placed', 'confirmed', 'preparing', 'ready', 'out-for-delivery', 'delivered', 'cancelled'];
    const categories = ['all', 'idli', 'dosa', 'benne_dosa', 'pesarattu', 'uttapam', 'upma', 'wada', 'bonda', 'poori', 'snacks'];
    const categoryLabels = { all: 'All', idli: 'Idli', dosa: 'Dosa', benne_dosa: 'Benne Dosa', pesarattu: 'Pesarattu', uttapam: 'Uttapam', upma: 'Upma', wada: 'Medhu Wada', bonda: 'Mysore Bonda', poori: 'Poori', snacks: 'Evening Snacks' };

    Admin.api = {
        baseUrl: location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? 'http://localhost:5001' : 'https://YOUR-PRODUCTION-BACKEND.onrender.com',
        async request(path, options = {}) {
            const request = { ...options, credentials: 'include', headers: { ...(options.headers || {}) } };
            if (request.body && typeof request.body !== 'string') { request.headers['Content-Type'] = 'application/json'; request.body = JSON.stringify(request.body); }
            const response = await fetch(`${this.baseUrl}${path}`, request);
            let payload = {};
            try { payload = await response.json(); } catch (error) { payload = {}; }
            if (!response.ok || payload.success === false) { const error = new Error(payload.message || payload.error?.message || payload.error || `Request failed (${response.status})`); error.status = response.status; throw error; }
            // Preserve pagination meta for list endpoints (loadOrders, loadStats rely on it)
            if (payload.meta) return { data: payload.data, meta: payload.meta };
            return Object.prototype.hasOwnProperty.call(payload, 'data') ? payload.data : payload;
        },
        get(path) { return this.request(path); }, post(path, body) { return this.request(path, { method: 'POST', body }); }, put(path, body) { return this.request(path, { method: 'PUT', body }); }, patch(path, body) { return this.request(path, { method: 'PATCH', body }); }, del(path) { return this.request(path, { method: 'DELETE' }); }
    };
    Admin.escapeHtml = (value) => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
    Admin.money = (value) => `₹${Math.round(Number(value) || 0)}`;
    Admin.ui = {
        toast(message, type = 'info') { const toast = document.createElement('div'); toast.className = `toast ${type}`; toast.textContent = message; $('#toast-region').appendChild(toast); window.setTimeout(() => toast.remove(), 3300); },
        setLoading(element, loading, message = 'Loading...') { if (!element) return; element.dataset.previousContent ||= element.innerHTML; element.innerHTML = loading ? `<div class="loading-state"><span class="spinner"></span> ${message}</div>` : element.dataset.previousContent; },
        confirm(title, message) { $('#confirm-title').textContent = title; $('#confirm-message').textContent = message; $('#confirm-backdrop').hidden = false; return new Promise((resolve) => { state.confirmResolver = resolve; }); },
        closeConfirm(result) { $('#confirm-backdrop').hidden = true; if (state.confirmResolver) state.confirmResolver(result); state.confirmResolver = null; },
        openDrawer() { $('#drawer-backdrop').hidden = false; requestAnimationFrame(() => { $('#drawer-backdrop').classList.add('is-open'); $('#order-drawer').classList.add('is-open'); }); $('#order-drawer').setAttribute('aria-hidden', 'false'); },
        closeDrawer() { $('#drawer-backdrop').classList.remove('is-open'); $('#order-drawer').classList.remove('is-open'); $('#order-drawer').setAttribute('aria-hidden', 'true'); window.setTimeout(() => { $('#drawer-backdrop').hidden = true; }, 300); }
    };
    Admin.auth = { me: () => Admin.api.get('/api/admin/me'), login: (username, password) => Admin.api.post('/api/admin/login', { username, password }), logout: () => Admin.api.post('/api/admin/logout') };

    const formatDate = (value, includeYear = true) => new Date(value).toLocaleString('en-IN', { day: '2-digit', month: 'short', ...(includeYear ? { year: 'numeric' } : {}), hour: 'numeric', minute: '2-digit' });
    const statusLabel = (value) => String(value || '').replaceAll('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
    const payLabel = (method) => ({
      cod: 'COD',
      razorpay: 'Razorpay',
      pay_at_counter: 'Pay at Counter',
    }[method] || String(method || 'COD'));
    const stars = (rating) => `${'★'.repeat(Math.max(0, Math.min(5, Number(rating) || 0)))}${'☆'.repeat(Math.max(0, 5 - (Number(rating) || 0)))}`;
    const empty = (message) => `<div class="empty-state"><i class="fa-regular fa-face-smile-beam" aria-hidden="true"></i><span>${Admin.escapeHtml(message)}</span></div>`;
    const statusBadge = (status) => `<span class="status-badge status-${Admin.escapeHtml(status)}">${Admin.escapeHtml(statusLabel(status))}</span>`;

    function setUser(admin) { $('#user-name').textContent = admin.name || admin.username; $('#user-role').textContent = admin.role || 'Admin'; $('#user-avatar').textContent = (admin.name || admin.username || 'A').charAt(0).toUpperCase(); $('#page-title').textContent = `Good morning, ${(admin.name || admin.username || 'Admin').split(/\s+/)[0]}.`; }
    function switchTab(tab) { state.tab = tab; $$('.nav-item').forEach((item) => item.classList.toggle('is-active', item.dataset.tab === tab)); $$('.panel').forEach((panel) => panel.classList.toggle('is-visible', panel.dataset.panel === tab)); $('#mobile-tab-name').textContent = tab.charAt(0).toUpperCase() + tab.slice(1); $('#sidebar').classList.remove('is-open'); if (tab === 'stats') loadStats(); if (tab === 'orders') loadOrders(); if (tab === 'menu') loadMenu(); if (tab === 'reviews') loadReviews(); if (tab === 'settings') loadRestaurant(); }

    async function loadStats() { try { const data = await Admin.api.get('/api/admin/stats'); $('#kpi-orders').textContent = data.ordersToday; $('#kpi-orders-note').textContent = `${data.totalOrders} total orders`; $('#kpi-completed').textContent = data.completedToday; $('#kpi-cancelled-note').textContent = `${data.cancelledToday} cancelled today`; $('#kpi-pending').textContent = data.pendingOrders; $('#kpi-pending').style.color = data.pendingOrders > 0 ? 'var(--marigold)' : ''; $('#kpi-rating').textContent = `${Number(data.avgRating || 0).toFixed(1)} ★`; $('#kpi-total-orders').textContent = `Across ${data.totalOrders} orders`; $('#kpi-revenue').textContent = Admin.money(data.revenueToday); $('#kpi-revenue-split').textContent = 'COD + Online + Counter'; $('#kpi-online-revenue').textContent = Admin.money(data.onlineRevenueToday); $('#kpi-cod-revenue').textContent = Admin.money(data.codRevenueToday); $('#kpi-counter-note').textContent = `Pay at counter: ${Admin.money(data.counterRevenueToday)}`; $('#kpi-menu-items').textContent = data.totalMenuItems; $('#kpi-menu-available').textContent = `${data.availableMenuItems} available`; const recent = await Admin.api.get('/api/admin/orders?limit=5&page=1'); renderRecentOrders(recent.data || []); const popular = await Admin.api.get('/api/admin/stats/popular-items?limit=5'); renderPopularItems(popular || []); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    function renderRecentOrders(orders) { const target = $('#recent-orders'); if (!orders.length) { target.innerHTML = empty('No orders have arrived yet.'); return; } target.innerHTML = `<table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>${orders.map((order) => `<tr><td><strong>${Admin.escapeHtml(order.orderNumber)}</strong><div class="subtle">${formatDate(order.createdAt, false)}</div></td><td>${Admin.escapeHtml(order.customer?.name || 'Guest')}</td><td><strong>${Admin.money(order.total)}</strong></td><td>${statusBadge(order.status)}</td></tr>`).join('')}</tbody></table>`; }
function renderPopularItems(items) { const target = $('#popular-items'); if (!target) return; if (!items.length) { target.innerHTML = empty('No order history yet.'); return; } target.innerHTML = `<table class="admin-table"><thead><tr><th>#</th><th>Item</th><th>Quantity sold</th><th>Revenue</th></tr></thead><tbody>${items.map((item, index) => `<tr><td><strong>${index + 1}</strong></td><td>${Admin.escapeHtml(item.name || 'Unknown item')}</td><td>${item.quantitySold}</td><td><strong>${Admin.money(item.revenue)}</strong></td></tr>`).join('')}</tbody></table>`; }

    function renderOrderFilters() { const counts = Object.fromEntries(statuses.map((status) => [status, 0])); state.orders.forEach((order) => { counts[order.status] = (counts[order.status] || 0) + 1; }); $('#order-filters').innerHTML = [['', 'All'], ...statuses.map((status) => [status, statusLabel(status)])].map(([value, label]) => `<button class="filter-chip ${state.orderStatus === value ? 'is-active' : ''}" data-order-filter="${value}">${label}<span class="count-badge">${value ? counts[value] : state.orderMeta.total || 0}</span></button>`).join(''); $$('#order-filters [data-order-filter]').forEach((button) => button.addEventListener('click', () => { state.orderStatus = button.dataset.orderFilter; state.orderPage = 1; loadOrders(); })); }
    async function loadOrders() { const target = $('#orders-list'); target.innerHTML = '<div class="loading-state"><span class="spinner"></span> Loading orders...</div>'; try { const query = new URLSearchParams({ page: state.orderPage, limit: 10 }); if (state.orderStatus) query.set('status', state.orderStatus); const result = await Admin.api.get(`/api/admin/orders?${query}`); state.orders = result.data || []; state.orderMeta = result.meta || {}; renderOrderFilters(); renderOrders(); renderPagination(); } catch (error) { target.innerHTML = empty(error.message); Admin.ui.toast(error.message, 'error'); } }
    function renderOrders() { const target = $('#orders-list'); if (!state.orders.length) { target.innerHTML = empty('No orders match this filter.'); return; } target.innerHTML = `<table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.orders.map((order) => { const first = order.items?.[0]; const extra = Math.max(0, (order.items?.length || 0) - 1); return `<tr data-order-row="${Admin.escapeHtml(order._id)}"><td><strong>${Admin.escapeHtml(order.orderNumber)}</strong><div class="subtle">${formatDate(order.createdAt)}</div></td><td><strong>${Admin.escapeHtml(order.customer?.name || 'Guest')}</strong><div class="subtle">${Admin.escapeHtml(order.customer?.phone || order.phone || '')}</div></td><td>${Admin.escapeHtml(first?.name || 'No items')} ×${first?.quantity || 0}${extra ? ` <span class="subtle">+${extra} more</span>` : ''}</td><td><strong>${Admin.money(order.total)}</strong></td><td><span class="pill">${Admin.escapeHtml(payLabel(order.paymentMethod))}</span></td><td><select class="status-select status-${Admin.escapeHtml(order.status)}" data-status-id="${Admin.escapeHtml(order._id)}" aria-label="Change order status">${statuses.map((status) => `<option value="${status}" ${status === order.status ? 'selected' : ''}>${statusLabel(status)}</option>`).join('')}</select></td><td><div class="card-actions"><button class="icon-button view-order" data-order-id="${Admin.escapeHtml(order._id)}" title="View order" aria-label="View order"><i class="fa-solid fa-eye"></i></button>${['placed', 'confirmed'].includes(order.status) ? `<button class="icon-button cancel-order" data-order-id="${Admin.escapeHtml(order._id)}" title="Cancel order" aria-label="Cancel order"><i class="fa-solid fa-ban"></i></button>` : ''}${['delivered', 'cancelled'].includes(order.status) ? `<button class="icon-button danger delete-order" data-order-id="${Admin.escapeHtml(order._id)}" title="Delete order" aria-label="Delete order"><i class="fa-solid fa-trash"></i></button>` : ''}</div></td></tr>`; }).join('')}</tbody></table>`; $$('#orders-list [data-status-id]').forEach((select) => select.addEventListener('change', () => updateOrderStatus(select.dataset.statusId, select.value, select))); $$('#orders-list .view-order').forEach((button) => button.addEventListener('click', () => openOrderDrawer(button.dataset.orderId))); $$('#orders-list .cancel-order').forEach((button) => button.addEventListener('click', () => cancelOrder(button.dataset.orderId))); $$('#orders-list .delete-order').forEach((button) => button.addEventListener('click', () => deleteOrderHandler(button.dataset.orderId))); }
    function renderPagination() { const target = $('#orders-pagination'); const pages = state.orderMeta.pages || 1; if (pages <= 1) { target.innerHTML = ''; return; } target.innerHTML = `<button ${state.orderPage <= 1 ? 'disabled' : ''} data-page="${state.orderPage - 1}"><i class="fa-solid fa-chevron-left"></i></button>${Array.from({ length: pages }, (_, index) => index + 1).map((page) => `<button class="${page === state.orderPage ? 'is-active' : ''}" data-page="${page}">${page}</button>`).join('')}<button ${state.orderPage >= pages ? 'disabled' : ''} data-page="${state.orderPage + 1}"><i class="fa-solid fa-chevron-right"></i></button>`; $$('#orders-pagination [data-page]').forEach((button) => button.addEventListener('click', () => { if (button.disabled) return; state.orderPage = Number(button.dataset.page); loadOrders(); })); }
    async function updateOrderStatus(id, status, select) { const previous = select.querySelector('option[selected]')?.value; try { await Admin.api.patch(`/api/admin/orders/${id}/status`, { status }); const order = state.orders.find((entry) => entry._id === id); if (order) order.status = status; select.className = `status-select status-${status}`; select.querySelectorAll('option').forEach((option) => option.toggleAttribute('selected', option.value === status)); Admin.ui.toast('Order updated', 'success'); loadStats(); } catch (error) { if (previous) select.value = previous; Admin.ui.toast(error.message, 'error'); } }
    async function cancelOrder(id) { if (!(await Admin.ui.confirm('Cancel this order?', 'The order will be marked as cancelled and the customer will see the update.'))) return; try { await Admin.api.patch(`/api/admin/orders/${id}/status`, { status: 'cancelled' }); Admin.ui.toast('Order cancelled', 'success'); await loadOrders(); loadStats(); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    async function deleteOrderHandler(id) { const order = state.orders.find((entry) => entry._id === id); const ok = await Admin.ui.confirm('Delete this order?', `${order?.orderNumber || 'This order'} will be permanently removed from the database. This cannot be undone.`); if (!ok) return; try { await Admin.api.del(`/api/admin/orders/${id}`); state.orders = state.orders.filter((entry) => entry._id !== id); renderOrders(); renderOrderFilters(); Admin.ui.toast('Order deleted', 'success'); loadStats(); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    async function openOrderDrawer(id) { const order = state.orders.find((entry) => entry._id === id); if (!order) return; $('#drawer-order-number').textContent = order.orderNumber; $('#order-drawer-body').innerHTML = `<div class="detail-block"><h3>Customer</h3><div class="detail-grid"><div><span>Name</span><b>${Admin.escapeHtml(order.customer?.name || 'Guest')}</b></div><div><span>Phone</span><b>${Admin.escapeHtml(order.customer?.phone || order.phone || 'Not provided')}</b></div><div><span>Placed</span><b>${formatDate(order.createdAt)}</b></div><div><span>Type</span><b>${Admin.escapeHtml(statusLabel(order.orderType))}</b></div></div></div>${order.orderType === 'delivery' ? `<div class="detail-block"><h3>Delivery address</h3><p>${Admin.escapeHtml(order.customerAddress?.line || order.address?.line1 || 'Address not provided')}<br>${Admin.escapeHtml(order.customerAddress?.area || order.address?.line2 || '')}<br>${Admin.escapeHtml(order.customerAddress?.city || order.address?.city || '')} ${Admin.escapeHtml(order.customerAddress?.pincode || order.address?.pincode || '')}</p></div>` : ''}<div class="detail-block"><h3>Items</h3><ul class="detail-items">${(order.items || []).map((item) => `<li><span>${Admin.escapeHtml(item.name)} × ${item.quantity}</span><b>${Admin.money(item.price * item.quantity)}</b></li>`).join('')}</ul><div class="detail-grid" style="margin-top:12px"><div><span>Subtotal</span><b>${Admin.money(order.subtotal)}</b></div><div><span>Delivery fee</span><b>${Admin.money(order.deliveryFee)}</b></div><div><span>Total</span><b>${Admin.money(order.total)}</b></div><div><span>Payment</span><b>${Admin.escapeHtml(payLabel(order.paymentMethod))} · ${Admin.escapeHtml(order.paymentStatus || 'pending')}</b></div></div></div>${order.notes ? `<div class="detail-block"><h3>Kitchen notes</h3><p>${Admin.escapeHtml(order.notes)}</p></div>` : ''}<div class="detail-block"><h3>Update status</h3><div class="drawer-status"><select id="drawer-status-select">${statuses.map((status) => `<option value="${status}" ${status === order.status ? 'selected' : ''}>${statusLabel(status)}</option>`).join('')}</select><button class="button button-primary" id="drawer-status-save">Save</button></div></div><div class="detail-block"><h3>Status timeline</h3><ul class="timeline">${(order.statusHistory || []).map((entry) => `<li><b>${Admin.escapeHtml(statusLabel(entry.status))}</b><small>${formatDate(entry.at || order.createdAt)}${entry.note ? ` · ${Admin.escapeHtml(entry.note)}` : ''}</small></li>`).join('')}</ul></div>`; $('#drawer-status-save').addEventListener('click', async () => { const select = $('#drawer-status-select'); await updateOrderStatus(id, select.value, select); $('#order-drawer').classList.contains('is-open') && Admin.ui.closeDrawer(); loadOrders(); }); Admin.ui.openDrawer(); }

    function renderMenuFilters() { $('#menu-filters').innerHTML = categories.map((category) => `<button class="filter-chip ${state.menuCategory.toLowerCase() === category.toLowerCase() ? 'is-active' : ''}" data-menu-filter="${Admin.escapeHtml(category)}">${Admin.escapeHtml(categoryLabels[category])}</button>`).join(''); $$('#menu-filters [data-menu-filter]').forEach((button) => button.addEventListener('click', () => { state.menuCategory = button.dataset.menuFilter; renderMenu(); renderMenuFilters(); })); }
    async function loadMenu() { $('#menu-list').innerHTML = '<div class="loading-state"><span class="spinner"></span> Loading menu...</div>'; try { state.menu = await Admin.api.get('/api/admin/menu'); renderMenuFilters(); renderMenu(); } catch (error) { $('#menu-list').innerHTML = empty(error.message); Admin.ui.toast(error.message, 'error'); } }
    function renderMenu() { const items = state.menu.filter((item) => state.menuCategory === 'all' || item.category.toLowerCase() === state.menuCategory.toLowerCase()); if (!items.length) { $('#menu-list').innerHTML = empty('No menu items in this category.'); return; } $('#menu-list').innerHTML = items.map((item) => `<article class="menu-admin-card"><div class="menu-thumb ${item.image ? '' : 'no-image'}">${item.image ? `<img src="${Admin.escapeHtml(item.image)}" alt="${Admin.escapeHtml(item.name)}" loading="lazy" class="menu-thumb-img">` : '<i class="fa-solid fa-bowl-food"></i>'}</div><div><h3>${Admin.escapeHtml(item.name)}</h3><p>${Admin.escapeHtml(item.description)}</p><div class="menu-meta"><span class="pill category-pill">${Admin.escapeHtml(item.category)}</span><strong>${Admin.money(item.price)}</strong></div><div class="toggle-row"><button class="mini-toggle available ${item.isAvailable ? 'is-on' : ''}" data-toggle-field="isAvailable" data-menu-id="${Admin.escapeHtml(item._id)}">${item.isAvailable ? 'Available' : 'Unavailable'}</button><button class="mini-toggle popular ${item.isPopular ? 'is-on' : ''}" data-toggle-field="isPopular" data-menu-id="${Admin.escapeHtml(item._id)}">${item.isPopular ? 'Popular' : 'Not popular'}</button></div></div><div class="card-actions"><button class="icon-button edit-menu" data-menu-id="${Admin.escapeHtml(item._id)}" aria-label="Edit ${Admin.escapeHtml(item.name)}"><i class="fa-solid fa-pen"></i></button><button class="icon-button delete-menu" data-menu-id="${Admin.escapeHtml(item._id)}" aria-label="Delete ${Admin.escapeHtml(item.name)}"><i class="fa-solid fa-trash"></i></button></div></article>`).join(''); $$('#menu-list [data-toggle-field]').forEach((button) => button.addEventListener('click', () => toggleMenuField(button.dataset.menuId, button.dataset.toggleField))); $$('#menu-list .edit-menu').forEach((button) => button.addEventListener('click', () => openMenuModal(button.dataset.menuId))); $$('#menu-list .delete-menu').forEach((button) => button.addEventListener('click', () => deleteMenuItem(button.dataset.menuId))); }
    async function toggleMenuField(id, field) { const item = state.menu.find((entry) => entry._id === id); if (!item) return; try { await Admin.api.put(`/api/admin/menu/${id}`, { [field]: !item[field] }); item[field] = !item[field]; renderMenu(); Admin.ui.toast('Menu item updated', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    function openMenuModal(id) { const form = $('#menu-form'); form.reset(); const item = state.menu.find((entry) => entry._id === id); $('#menu-modal-title').textContent = item ? 'Edit menu item' : 'Add menu item'; form.elements.id.value = item?._id || ''; if (item) { ['name', 'description', 'price', 'category', 'image', 'spicyLevel', 'sortOrder'].forEach((field) => { if (form.elements[field]) form.elements[field].value = item[field] ?? ''; }); form.elements.tags.value = (item.tags || []).join(', '); form.elements.isVeg.checked = item.isVeg; form.elements.isAvailable.checked = item.isAvailable; form.elements.isPopular.checked = item.isPopular; } updateImagePreview(); $('#modal-backdrop').hidden = false; }
    function updateImagePreview() { const url = $('#menu-form').elements.image.value.trim(); $('#image-preview').innerHTML = url ? `<img src="${Admin.escapeHtml(url)}" alt="">` : ''; }
    async function saveMenuItem(event) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = { name: String(data.get('name')).trim(), description: String(data.get('description')).trim(), price: Number(data.get('price')), category: data.get('category'), image: String(data.get('image') || '').trim(), isVeg: data.has('isVeg'), isAvailable: data.has('isAvailable'), isPopular: data.has('isPopular'), spicyLevel: Number(data.get('spicyLevel')), tags: String(data.get('tags') || '').split(',').map((tag) => tag.trim()).filter(Boolean), sortOrder: Number(data.get('sortOrder') || 0) }; if (!payload.name || !payload.description || Number.isNaN(payload.price) || payload.price < 0 || !categories.slice(1).includes(payload.category)) return Admin.ui.toast('Enter a name, description, valid price, and category', 'error'); try { if (data.get('id')) await Admin.api.put(`/api/admin/menu/${data.get('id')}`, payload); else await Admin.api.post('/api/admin/menu', payload); $('#modal-backdrop').hidden = true; await loadMenu(); Admin.ui.toast('Menu item saved', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    async function deleteMenuItem(id) { const item = state.menu.find((entry) => entry._id === id); if (!(await Admin.ui.confirm('Delete menu item?', `${item?.name || 'This item'} will be removed from the catalogue.`))) return; try { await Admin.api.del(`/api/admin/menu/${id}`); state.menu = state.menu.filter((entry) => entry._id !== id); renderMenu(); Admin.ui.toast('Menu item deleted', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }

    async function loadReviews() { $('#pending-reviews').innerHTML = '<div class="loading-state"><span class="spinner"></span> Loading...</div>'; $('#approved-reviews').innerHTML = ''; try { const [pending, approved] = await Promise.all([Admin.api.get('/api/admin/reviews?approved=false'), Admin.api.get('/api/admin/reviews')]); state.pendingReviews = pending || []; state.approvedReviews = (approved || []).filter((review) => review.isApproved); renderReviews(); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    function reviewCard(review, pending) { return `<article class="review-card" data-review-id="${Admin.escapeHtml(review._id)}"><div class="review-card-head"><b>${Admin.escapeHtml(review.name)}</b><span class="stars" aria-label="${review.rating} out of 5">${stars(review.rating)}</span></div><p>${Admin.escapeHtml(review.message)}</p><div class="subtle">${formatDate(review.createdAt)}</div><div class="review-actions" style="margin-top:12px">${pending ? `<button class="text-button approve-review" data-review-id="${Admin.escapeHtml(review._id)}">Approve</button>` : ''}<button class="text-button danger delete-review" data-review-id="${Admin.escapeHtml(review._id)}">Delete</button></div></article>`; }
    function renderReviews() { $('#pending-review-count').textContent = state.pendingReviews.length; $('#pending-reviews').innerHTML = state.pendingReviews.length ? state.pendingReviews.map((review) => reviewCard(review, true)).join('') : empty('No pending reviews.'); $('#approved-reviews').innerHTML = state.approvedReviews.length ? state.approvedReviews.map((review) => reviewCard(review, false)).join('') : empty('No approved reviews yet.'); $$('.approve-review').forEach((button) => button.addEventListener('click', () => approveReview(button.dataset.reviewId))); $$('.delete-review').forEach((button) => button.addEventListener('click', () => deleteReview(button.dataset.reviewId))); }
    async function approveReview(id) { try { await Admin.api.patch(`/api/admin/reviews/${id}/approve`, {}); const review = state.pendingReviews.find((entry) => entry._id === id); state.pendingReviews = state.pendingReviews.filter((entry) => entry._id !== id); if (review) { review.isApproved = true; state.approvedReviews.unshift(review); } renderReviews(); Admin.ui.toast('Review approved', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    async function deleteReview(id) { const review = [...state.pendingReviews, ...state.approvedReviews].find((entry) => entry._id === id); if (!(await Admin.ui.confirm('Delete this review?', `Remove the review from ${review?.name || 'this guest'} permanently.`))) return; try { await Admin.api.del(`/api/admin/reviews/${id}`); state.pendingReviews = state.pendingReviews.filter((entry) => entry._id !== id); state.approvedReviews = state.approvedReviews.filter((entry) => entry._id !== id); renderReviews(); Admin.ui.toast('Review deleted', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }

    async function loadRestaurant() { try { const restaurant = await Admin.api.get('/api/restaurant'); state.restaurant = restaurant; const form = $('#settings-form');['name', 'hindiName', 'tagline', 'phone', 'whatsapp', 'email', 'address', 'plusCode', 'mapsQuery', 'swiggyUrl', 'deliveryFee', 'minOrder', 'rating', 'reviewCount'].forEach((field) => { if (form.elements[field]) form.elements[field].value = restaurant[field] ?? ''; }); form.elements.open.value = restaurant.hours?.open || ''; form.elements.close.value = restaurant.hours?.close || ''; form.elements.isAcceptingOrders.checked = Boolean(restaurant.isAcceptingOrders); $$('#days-open input').forEach((input) => { input.checked = (restaurant.hours?.daysOpen || []).includes(input.value); }); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    async function saveRestaurant(event) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = {};['name', 'hindiName', 'tagline', 'phone', 'whatsapp', 'email', 'address', 'plusCode', 'mapsQuery', 'swiggyUrl'].forEach((field) => { payload[field] = String(data.get(field) || '').trim(); }); payload.hours = { open: data.get('open'), close: data.get('close'), daysOpen: $$('#days-open input:checked').map((input) => input.value) };['deliveryFee', 'minOrder', 'rating', 'reviewCount'].forEach((field) => { payload[field] = Number(data.get(field) || 0); }); payload.isAcceptingOrders = data.has('isAcceptingOrders'); try { await Admin.api.put('/api/admin/restaurant', payload); Admin.ui.toast('Settings saved', 'success'); } catch (error) { Admin.ui.toast(error.message, 'error'); } }
    function buildDays() { $('#days-open').innerHTML = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => `<label class="day-option"><input type="checkbox" value="${day}">${day}</label>`).join(''); }

    function bindEvents() { $$('.nav-item').forEach((button) => button.addEventListener('click', () => switchTab(button.dataset.tab))); $$('[data-go-tab]').forEach((button) => button.addEventListener('click', () => switchTab(button.dataset.goTab))); $('#sidebar-toggle').addEventListener('click', () => $('#sidebar').classList.toggle('is-open')); $('#logout-button').addEventListener('click', async () => { try { await Admin.auth.logout(); } finally { location.reload(); } }); $('#orders-refresh').addEventListener('click', loadOrders); $('#reviews-refresh').addEventListener('click', loadReviews); $('#add-menu-item').addEventListener('click', () => openMenuModal()); $('#menu-form').addEventListener('submit', saveMenuItem); $('#menu-form').elements.image.addEventListener('input', updateImagePreview); $('#settings-form').addEventListener('submit', saveRestaurant); $('#confirm-cancel').addEventListener('click', () => Admin.ui.closeConfirm(false)); $('#confirm-accept').addEventListener('click', () => Admin.ui.closeConfirm(true)); $('#drawer-backdrop').addEventListener('click', () => Admin.ui.closeDrawer()); $$('[data-close-drawer]').forEach((button) => button.addEventListener('click', () => Admin.ui.closeDrawer())); $$('[data-close-modal]').forEach((button) => button.addEventListener('click', () => { $('#modal-backdrop').hidden = true; })); document.addEventListener('keydown', (event) => { if (event.key !== 'Escape') return; Admin.ui.closeDrawer(); $('#modal-backdrop').hidden = true; Admin.ui.closeConfirm(false); }); }
    function showApp(admin) { setUser(admin); $('#login-screen').hidden = true; $('#app-shell').hidden = false; switchTab('stats'); }
    document.addEventListener('DOMContentLoaded', async () => { buildDays(); bindEvents(); $('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); $('#login-error').hidden = true; try { const admin = await Admin.auth.login(String(data.get('username')).trim(), String(data.get('password'))); showApp(admin); Admin.ui.toast('Welcome back', 'success'); } catch (error) { $('#login-error').textContent = error.status === 401 ? 'Invalid username or password.' : error.message; $('#login-error').hidden = false; } }); $('.password-toggle').addEventListener('click', (event) => { const input = event.currentTarget.closest('.input-with-action').querySelector('input'); const visible = input.type === 'password'; input.type = visible ? 'text' : 'password'; event.currentTarget.innerHTML = `<i class="fa-solid fa-eye${visible ? '-slash' : ''}" aria-hidden="true"></i>`; }); try { const admin = await Admin.auth.me(); showApp(admin); } catch (error) { $('#login-screen').hidden = false; $('#app-shell').hidden = true; } });
})();
